src/RetailMgmt.WebMVC/Models/ErrorViewModel.cs
using System;

namespace RetailMgmt.WebMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/RetailMgmt.WebMVC/Controllers/CurrencyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RetailMgmt.Application.ViewModels.OrganizationModule.Currency;

namespace RetailMgmt.WebMVC.Controllers
{
    public class CurrencyController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new CurrencyCreateViewModel());
        }

        [HttpPost]
        public IActionResult Create(CurrencyCreateViewModel model)
        {
            if(ModelState.IsValid)
            {

            }
            return View();
        }
    }
}

src/RetailMgmt.WebMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RetailMgmt.Application.Dtos.OrganizationModule.Currency;
using RetailMgmt.Application.Interfaces.OrganizationModule.Currency;
using RetailMgmt.WebMVC.Models;
using System.Diagnostics;
using System.Threading.Tasks;

namespace RetailMgmt.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICurrencyService _currencyService;
        public HomeController(ILogger<HomeController> logger, ICurrencyService currencyService)
        {
            _logger = logger;
            _currencyService = currencyService;
        }

        public async Task<IActionResult> Index()
        {
            //var test = await _currencyService.GetPagedListAsync(new CurrencyListInputDto{ PageNumber = 0, PageSize = 1 });
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/RetailMgmt.WebMVC/Views/Currency/Create.cshtml
@using RetailMgmt.Application.ViewModels.OrganizationModule.Currency;
@model CurrencyCreateViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form method="post" asp-controller="Currency" asp-action="Create">
    <label>Code</label>
    <input asp-for="Code" class="form-control form-input" type="text" />
    <br />
    <label>Description</label>
    <input asp-for="Description" class="form-control form-input" type="text" />
    <br />
    <input type="submit" value="Save" />
</form>

src/RetailMgmt.WebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/RetailMgmt.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RetailMgmt.WebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RetailMgmt.WebMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RetailMgmt.WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>